// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_aereopuerto.Modelos;

namespace api_aereopuerto.Migrations
{
    [DbContext(typeof(BaseDatos))]
    partial class BaseDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api_aereopuerto.Modelos.Avion", b =>
                {
                    b.Property<int>("AvionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacidad");

                    b.Property<string>("Codigo");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.HasKey("AvionId");

                    b.ToTable("Aviones");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Base", b =>
                {
                    b.Property<int>("BaseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ciudad");

                    b.Property<string>("Direccion");

                    b.Property<string>("Nombre");

                    b.HasKey("BaseId");

                    b.ToTable("Bases");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Mantenimiento", b =>
                {
                    b.Property<int>("MantenimientoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvionId");

                    b.Property<int>("BaseId");

                    b.Property<string>("Detalle");

                    b.Property<string>("Fecha");

                    b.HasKey("MantenimientoId");

                    b.HasIndex("AvionId");

                    b.HasIndex("BaseId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Miembro", b =>
                {
                    b.Property<int>("MiembroId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Cedula");

                    b.Property<string>("Ciudad");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("MiembroId");

                    b.ToTable("Miembros");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Piloto", b =>
                {
                    b.Property<int>("PilotoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Codigo");

                    b.Property<double>("HorasVuelo");

                    b.Property<string>("Nombre");

                    b.HasKey("PilotoId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Tripulacion", b =>
                {
                    b.Property<int>("TripulacionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MiembroId");

                    b.Property<int>("VueloId");

                    b.HasKey("TripulacionId");

                    b.HasIndex("MiembroId");

                    b.HasIndex("VueloId");

                    b.ToTable("Tripulaciones");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Vuelo", b =>
                {
                    b.Property<int>("VueloId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvionId");

                    b.Property<string>("Codigo");

                    b.Property<int>("PilotoId");

                    b.Property<string>("ciudadDestino");

                    b.Property<string>("ciudadOrigen");

                    b.Property<string>("fechaLlegada");

                    b.Property<string>("fechaSalida");

                    b.HasKey("VueloId");

                    b.HasIndex("AvionId");

                    b.HasIndex("PilotoId");

                    b.ToTable("Vuelos");
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Mantenimiento", b =>
                {
                    b.HasOne("api_aereopuerto.Modelos.Avion", "Aviones")
                        .WithMany()
                        .HasForeignKey("AvionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("api_aereopuerto.Modelos.Base", "Bases")
                        .WithMany()
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Tripulacion", b =>
                {
                    b.HasOne("api_aereopuerto.Modelos.Miembro", "Miembros")
                        .WithMany()
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("api_aereopuerto.Modelos.Vuelo", "Vuelos")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api_aereopuerto.Modelos.Vuelo", b =>
                {
                    b.HasOne("api_aereopuerto.Modelos.Avion", "Aviones")
                        .WithMany()
                        .HasForeignKey("AvionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("api_aereopuerto.Modelos.Piloto", "Pilotos")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
